name: SonarQube Analysis

# Trigger the workflow on push to the main branch
on:
  push:
    branches:
      - main  # Change this to the branch you want (e.g., 'develop')

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up JDK (SonarScanner requires Java)
      - name: Set up JDK 11 (AdoptOpenJDK / Adoptium)
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Specify the JDK version you need
          distribution: 'adoptopenjdk'  # Use Adoptium (AdoptOpenJDK) distribution

      # Step 3: Install SonarQube Scanner (run the Docker container)
      - name: Run SonarQube Scan
        run: |
          docker run --rm -e SONAR_LOGIN="${{ secrets.SONAR_TOKEN }}" --network="host" \
          -v $(pwd):/usr/src -v $(pwd)/scanner-cache:/usr/src/output sonarsource/sonar-scanner-cli
